### PR TITLE
Expose verify parameter on dbapi.connect

### LINKED ISSUE #29: Allow to specify client certificate path explicitly
As per discussion in Slack: https://prestosql.slack.com/archives/CFPVDCDHV/p1589924393017200

Currently presto.dbapi.connect api does not have a parameter to explicitly specify client certificate path to connect with SSL/TLS. Client cert should be explicitly configurable.

### PR DESCRIPTION
**Pull request by caiopavanelli**
This PR exposes the verify parameter to explicitly specify client certificate path.

This resolves #29

### CODE REVIEW

**Comment by caiopavanelli** [comment]
Hi there, I've just submitted the individual CLA for approval. My employer Simbiose Ventures will (or already have) also submit the corporate CLA. Thanks!

**Comment by martint** [comment]
@cla-bot check

**Comment by electrum** [comment]
Thanks!

**Comment by findepi** [comment]
Released in `0.301.0`

**Pull request merged**
