### PR TITLE
Removed redirect_handler

### LINKED ISSUE #26: Remove redirect_handler
https://github.com/prestosql/presto-python-client/pull/23#issuecomment-620918048 @electrum 

> I think the purpose of `GatewayRedirectHandler` is to canonicalize the hostname in the URL, likely for a reason related to Kerberos or TLS certificates. However, this seems like the wrong place to handle it. I suggest removing the redirect handler support entirely.

https://github.com/prestosql/presto-python-client/pull/23#issuecomment-621007601 @findepi 

> @electrum i agree, my assessment of the redirect handler is the same. 
Let's do small steps, just in case someone relied on this.
I will merge as is, and create follow up issue to remove the redirect handler altogether.

### PR DESCRIPTION
**Pull request by iadi7ya**
Fixes #26 

Removed redirect_handler support

### CODE REVIEW

**Comment by iadi7ya** [comment]
test this please

**Comment by martint** [comment]
@cla-bot check

**Review by findepi — APPROVED** [review]
LGTM. @iadi7ya can you please rebase and squash the commits into one?

If you haven't used git rebase previously, https://docs.github.com/en/free-pro-team@latest/github/using-git/about-git-rebase might be helpful.

**Comment by iadi7ya** [comment]
@findepi Thanks for sharing this document as I haven't tried rebase and squash before as I am new to OS contributions.

**Comment by iadi7ya** [comment]
> LGTM. @iadi7ya can you please rebase and squash the commits into one?

Hi @findepi  It worked finally. Thanks!

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
Merged, thanks!

**Comment by iadi7ya** [comment]
Thanks!

**Pull request merged**
